spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/secondClosetClub
          jwk-set-uri: http://localhost:8083/auth/realms/secondClosetClub/protocol/openid-connect/certs
  datasource:
    username: admin
    password: LucidAN21&
    url: jdbc:mysql://scc.cxnse0qgwvdu.eu-west-1.rds.amazonaws.com:3306/resource-local
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    url: jdbc:mysql://scc.cxnse0qgwvdu.eu-west-1.rds.amazonaws.com:3306
    schemas: resource-local
    user: admin
    password: TEST
    enabled: true