server:
  port: 8084
  servlet:
    context-path: /resource-server

logging:
  level:
    org:
      springframework:
        security: ${SECURITY_LOGGING_LEVEL:info}

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: '/api/public/service-info'

---

keycloak:
  realm: SecondClosetClub
  resource: frontEnd
  public-client: true
  ssl-required: none
  cors: true
  bearer-only: true
  use-resource-role-mappings: true
  security-constraints:
    - authRoles:
        - scc_user_role
      security-collections:
        - name: Logged in endpoint
        - patterns:
            - /api/private/*
    - authRoles:
        - scc_admin_role
      security-collections:
        - name: Admin only endpoints
          patterns:
            - /api/admin/*