server: 
  port: 8081
  servlet: 
    context-path: /resource-server

logging:
  level:
    org:
      springframework:
        security: DEBUG

        spring:
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://quick-fix-needs-to-be-removed
  flyway:
    enabled: false