server:
  port: 8084
  servlet:
    context-path: /resource-server

logging:
  level:
    org:
      springframework:
        security: DEBUG

        spring:
spring:
  flyway:
    enabled: false
---

logging:
  level:
    org:
      springframework:
        security: ${SECURITY_LOGGING_LEVEL:info}

keycloak:
  auth-server-url: http://localhost:8083/auth
  realm: SecondClosetClub
  resource: frontEnd
  public-client: true
  ssl-required: none
  cors: true
  bearer-only: true
  use-resource-role-mappings: true
  security-constraints:
    - authRoles:
        - scc_user_role
      security-collections:
        - name: Logged in endpoint
        - patterns:
            - /api/private/*
    - authRoles:
        - scc_admin_role
      security-collections:
        - name: Admin only endpoints
          patterns:
            - /api/admin/*
management:
  endpoints:
    web:
      exposure:
        include: '*'