spring:
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}/${DB_SCHEMA_NAME}jdbc:mysql://scc.cxnse0qgwvdu.eu-west-1.rds.amazonaws.com:3306/resource-local
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    url: ${DB_URL}jdbc:mysql://scc.cxnse0qgwvdu.eu-west-1.rds.amazonaws.com:3306
    schemas: ${DB_SCHEMA_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    enabled: true
scc:
  bucket:
    name: ${S3_BUCKET_NAME}
    url: ${S3_BUCKET_URL} https://second-closet-club-images.s3.eu-west-1.amazonaws.com
    region: eu-west-1
    accessKey: ${S3_ACCESS_KEY}
    secretKey: ${S3_SECRET_KEY}

---
keycloak-client:
  server-url: ${KEYCLOAK_BASE_URI}
  username: ${KEYCLOAK_CLIENT_USER_NAME}
  password: ${KEYCLOAK_CLIENT_USER_PASSWORD}
  clientId: b88ce206-63d6-43b6-87c9-ea09d8c02f32
  roleUserId: c9efed4b-9edd-486d-a16f-dc5654ddf0b7
  roleActiveMemberId: 4547c5d2-eb03-426f-bf3b-d7bf9a1a76dc

keycloak:
  auth-server-url:  ${KEYCLOAK_BASE_URI}
  proxyUrl: ${KEYCLOAK_PROXY_URI}