server:
  port: 8084
  servlet:
    context-path: /resource-server

logging:
  level:
    org:
      springframework:
        security: DEBUG

        spring:
spring:
  flyway:
    enabled: false
---

keycloak-client:
  server-url: http://localhost:8083/auth
  username: masterapiuser
  password: masterapiuser
  clientId: 276928b9-4218-4443-bec7-956b20a610b0
  roleId: 23aa99f0-6e9d-46fa-8bbd-51902da41834
---

keycloak:
  auth-server-url: http://localhost:8083/auth
  realm: SecondClosetClub
  resource: frontEnd
  public-client: true
  ssl-required: none
  cors: true
  bearer-only: true
  use-resource-role-mappings: true
  security-constraints:
    - authRoles:
        - scc_user_role
      security-collections:
        - name: Logged in endpoint
        - patterns:
            - /api/private/*
    - authRoles:
        - scc_admin_role
      security-collections:
        - name: Admin only endpoints
          patterns:
            - /api/admin/*