spring:
  datasource:
    username: admin
    password: TESTING
    url: jdbc:mysql://scc.cxnse0qgwvdu.eu-west-1.rds.amazonaws.com:3306/resource-local
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    url: jdbc:mysql://scc.cxnse0qgwvdu.eu-west-1.rds.amazonaws.com:3306
    schemas: resource-local
    user: admin
    password: TESTING
    enabled: true

scc:
  bucket:
    name: second-closet-club-images-local
    url: https://second-closet-club-images-local.s3.eu-west-1.amazonaws.com