spring:
  datasource:
    username: admin
    password: TESTING
    url: jdbc:mysql://scc.cxnse0qgwvdu.eu-west-1.rds.amazonaws.com:3306/resource
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    url: jdbc:mysql://scc.cxnse0qgwvdu.eu-west-1.rds.amazonaws.com:3306
    schemas: resource
    user: admin
    password: TESTING
    enabled: true
scc:
  bucket:
    name: second-closet-club-images
    url: https://second-closet-club-images.s3.eu-west-1.amazonaws.com
    region: eu-west-1
    accessKey: AKIAVLRFY5LDBZ7WPU6D
    secretKey: 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

---

keycloak-client:
  server-url: http://localhost:8083/auth
  username: masterapiuser
  password: masterapiuser
  clientId: b88ce206-63d6-43b6-87c9-ea09d8c02f32
  roleId: 9f897986-73e0-46b7-a5f3-5c2a6235b4ce