CREATE TABLE IF NOT EXISTS  product (
    ID INT PRIMARY KEY AUTO_INCREMENT ,
    NAME varchar(256),
    ID_PRODUCT_CATEGORY INT,
    ID_SEASON INT,
    ID_COLOR INT,
    ID_COVER_IMG INT,
    DRY_CLEAN BOOLEAN ,
    RETAIL_PRICE double,
    TYPE varchar(256),
    QUICK_DESC varchar(256),
    MATERIAL varchar(256),
    DESCRIPTION varchar(256),
    FITTING_INFO varchar(256),
    WASH_INFO varchar(256),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS  product_category (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME varchar(256)
);

CREATE TABLE IF NOT EXISTS  product_occasion (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUCT INT,
    ID_OCCASION INT
);


CREATE TABLE IF NOT EXISTS  product_size (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUCT INT,
    ID_SIZE INT
);

CREATE TABLE IF NOT EXISTS  product_measurement (
    ID_PRODUCT INT PRIMARY KEY ,
    LENGTH INT,
    HIPS INT,
    WAIST INT,
    CHEST INT
);

CREATE TABLE IF NOT EXISTS  product_image (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUCT INT,
    ID_IMAGE INT
);

CREATE TABLE IF NOT EXISTS  image (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PATH varchar(1000)
);

CREATE TABLE IF NOT EXISTS  occasion (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME varchar(256)
);

CREATE TABLE IF NOT EXISTS  size (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME varchar(256)
);

CREATE TABLE IF NOT EXISTS  color(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME varchar(256)
);

CREATE TABLE IF NOT EXISTS  season(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME varchar(256)
);

CREATE TABLE IF NOT EXISTS  booking_request(
    ID INT PRIMARY KEY AUTO_INCREMENT ,
    ID_USER varchar (36)NOT NULL,
    ID_PRODUCT INT NOT NULL,
    ID_PRODUCT_SIZE INT NOT NULL,
    START_DATE DATE NOT NULL,
    COLLECTION_PLACE varchar (256),
    STATUS ENUM ('WAITING_COLLECTION','ACTIVE','WAITING_RETURN', 'COMPLETE'),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS  personal_info(
    ID INT PRIMARY KEY AUTO_INCREMENT ,
    ID_USER varchar (36) NOT NULL UNIQUE ,
    FIRST_NAME varchar (50) NOT NULL,
    LAST_NAME varchar (50) NOT NULL,
    PHONE varchar (10) NOT NULL,
    EMAIL varchar (75) NOT NULL UNIQUE ,
    DOB DATE NOT NULL,
    COUNTRY varchar (75) NOT NULL,
    CITY varchar (75) NOT NULL,
    EIRCODE varchar (20) NOT NULL,
    ADDRESS_LINE_ONE varchar (75) NOT NULL,
    ADDRESS_LINE_TWO varchar (75) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
